services:
  mysql-db:
    image: mysql:lts
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: roomify
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-roomify
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 3
      timeout: 5s

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
