version: '3.8'

services:
  db-project-iseng-laravel:
    image: mysql:lts
    container_name: db-project-iseng-laravel
    ports:
      - protocol: tcp
        published: 3306
        target: 3306
#   ports:
#     - "3306:3306"
    environment:
      MYSQL_USER: bukan_admin
      MYSQL_PASSWORD: rahasia
      MYSQL_ROOT_PASSWORD: rahasia_admin
      MYSQL_DATABASE: db-project-iseng-laravel
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-project-iseng-laravel:/var/lib/mysql
    networks:
      - network-db-project-iseng-laravel
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 600m
        limits:
          cpus: "1"
          memory: 1g

networks:
  network-db-project-iseng-laravel:
    name: network-db-project-iseng-laravel
    driver: bridge

volumes:
  db-project-iseng-laravel:
    name: db-project-iseng-laravel